name: Project Management CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        database_url: ${{ DATABASE_URL }}
        base_email: ${{ BASE_EMAIL }}
        
    - run: yarn install --frozen-lockfile
    #start test
    - run: yarn test
