name: Project Management CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        BASE_EMAIL: ${{ secrets.BASE_EMAIL }}
        BASE_PASS:  ${{ secrets.BASE_PASS }}
        NODE_ENV : ${{ secrets.NODE_ENV }}
        PORT  :     ${{ secrets.PORT }}
        JWT_SECRETKEY :  ${{ secrets.JWT_SECRETKEY }}
        JWT_EMAIL_EXPIRES :    ${{ secrets.JWT_EMAIL_EXPIRES }}
        JWT_SIGNIN_EXPIRES :    ${{secrets.JWT_SIGNIN_EXPIRES }}
        COOKIE_SESSION_KEY1 :  ${{ secrets.COOKIE_SESSION_KEY1 }}
        COOKIE_SESSION_KEY2 :  ${{ secrets.COOKIE_SESSION_KEY2 }}
        GOOGLE_CLIENT_ID :     ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET :  ${{ secrets.GOOGLE_CLIENT_SECRET}}
        HOME_URL :   ${{ secrets.HOME_URL }}
        FACEBOOK_CLIENT_ID : ${{ secrets.FACEBOOK_CLIENT_ID }}
        FACEBOOK_CLIENT_SECRET :   ${{ secrets.FACEBOOK_CLIENT_SECRET }}
        FACEBOOK_CALLBACK_URL :  ${{ secrets.FACEBOOK_CALLBACK_URL }}
        CLOUDINARY_CLOUDNAME  :  ${{ secrets.CLOUDINARY_CLOUDNAME }}
        CLOUDINARY_APIKEY :  ${{ secrets.CLOUDINARY_APIKEY }}
        CLOUDINARY_APISECRET :  ${{ secrets.CLOUDINARY_APISECRET }}
        
    - run: yarn install --frozen-lockfile
    #start test
    - run: yarn test
